### ISSUE TITLE
Research: GUI Options

### ISSUE THREAD

**Issue by tuckplace** [cs-utulsa/Encrypted-Chat-Service#14]
Need to look into options for a GUI from our chose language. How usable or customizable is the built in one? Is there a better off the shelf solution here? None of us specialize in UI, so we need this to be quick and easy to use.  Python is our language of choice.

- [x] Analysis of build in UI, is it doable? Too complex?
- [x] Potential off the shelf options with pros/comes

**Comment by dawsonjones2020** [comment]
Python's Tkinter module has really nice built-in tools for designing a GUI. It also has good documentation and I have experience with it.

**Comment by mypleasure370** [comment]
I've worked in HTML and CSS in the past if we need to default to a web-app type of UI

**Comment by dawsonjones2020** [comment]
# Tkinter
## Pros
- I have a good amount of experience with it
- Already built-in to Python - no download required
- Coding is simple
- Uses native widgets to Mac and Windows
- Good documentation
## Cons
- Not the best looking out of the box, but the [ttkbootstrap](https://ttkbootstrap.readthedocs.io/en/latest/) module fixes that issue with one line of code. It also offers several themes to choose between
- Code gets a little ugly if it's not handled properly
- Supports Linux but requires a few extra [steps](https://www.geeksforgeeks.org/how-to-install-tkinter-on-linux/)

# PyQT 5
## Pros
- Good documentation
- Coding is simple
- Has more UI [components](https://zetcode.com/gui/pyqt5/widgets/)

## Cons
- Steep learning curve
- Requires separate download (not a big deal since we can just package it ourselves)
- "You have to pay for a commercial license if your application is not open-source" (I don't know if that applies to us or not but I found that quote online)

# Kivy
## Pros
- Easily supports mobile
- No platform-specific code

## Cons
- No OS-native interfaces
- Less documentation
- Package size is much larger because Python is packaged with it (I might be able to get around this though)

**Comment by dawsonjones2020** [comment]
Also, this is the [tool](https://pynsist.readthedocs.io/en/latest/) I use to convert the python file to an exe. It's super simple to use and lets you make executables for windows, linux, and mac. It should work with any of these GUI options so that shouldn't factor into our decision. I have only used it with tkinter apps before, but it shouldn't be too hard to make it work with the other two if we go with one of those options.
